config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'

  resources :projects, only: %i[index show], param: :name

  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @projects = Project.all.where(featured?: true)
  end

  def about; end
  def contact; end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: :show

  def index
    @projects = Project.all.order(name: :desc)
  end

  def show
    @project = Project.find_by(name: params[:name])
  end

  private

  def set_project
    @project = Project.find_by(name: params[:name])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>jaxxon.dev</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <base target="_blank">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-primary flex flex-col flex-1 grow text-secondary min-h-screen p-2">
    <%= render 'shared/header' %>
    <main class="container flex-1 mx-auto mt-16 px-5 flex">
      <%= yield %>
    </main>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container justify-center flex">
  <div class="flex flex-col h-fit w-3/5 justify-center border p-10">
    <div class="p-1">
      <img class="rounded-full mx-auto border-secondary border-2 w-2/5" src="https://avatars.githubusercontent.com/u/63265212?v=4" alt="picture of jaxxon">
    </div>
    <div class="text-center leading-relaxed py-2 text-lg">
      <p class="text-2xl font-bold py-3">Hi, I'm jaxxon 👋</p>
      <p class="py-2">I am a junior developer from the Netherlands.
        I like to play my guitar, cook a good meal, and code.
        This site hosts a showcase of projects I have worked on.
        Feel free to have <%= link_to 'a look around!', projects_path, class: 'link' %></p>
      <p>If you want to work together on a project, <%= link_to 'please reach out.', contact_path, class: 'link' %></p>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container">
  <h1 class='text-3xl py-5'>Some selected projects:</h1>
  <div class="cards">
    <%= render 'shared/card' %>
  </div>
</div>

app/views/projects/index.html.erb
<div class="container">
  <div class="cards">
    <%= render 'shared/card' %>
  </div>
</div>

app/views/projects/show.html.erb
<div class="container">
  <div class="relative project border border-secondary rounded-2xl">
    <div class="relative pb-1/3 hover:pb-1/2 transition-all delay-200">
      <img class='project-image-url rounded-t-2xl absolute h-full w-full object-cover' src=<%=@project.image_url%> alt="card image">
    </div>
    <div class='relative flex flex-col px-10 py-8'>
      <div class='text-4xl pb-3 font-bold'><%= @project.name.capitalize %></div>
      <div class='flex flex-row gap-2'>
        <% @project.language.each do |lang| %>
          <div class='rounded-xl border border-secondary font-mono text-center w-fit px-5 py-1 my-1'>
            <%= lang %>
          </div>
        <% end %>
      </div>
      <p class='py-8 font-mono'><%= @project.description %></p>
      <div class='absolute font-mono top-0 right-0 p-5 border rounded-bl-2xl border-b-secondary border-l-secondary border-t-0 border-r-0'>
        <%= link_to 'View git repo', @project.git_link %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_card.html.erb
<% @projects.each do |project| %>
  <div class="card">
    <div class="relative pb-2/3">
      <img class='project-image-url absolute h-full w-full object-cover' src=<%=project.image_url%> alt="card image">
    </div>
    <div class="p-5">
      <div class="project-name"><%= link_to project.name.capitalize, project_path(project.name)%></div>
      <%= link_to 'Read more', project_path(project.name), class: 'button button-inv' %>
    </div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">

  <div class="footer-row">
    <a class="footer-item" href='https://github.com/noxxaj'>
      <box-icon type='logo' name='github' color='white' size='2em'></box-icon>
      <p>Github</p>
    </a>
    <a class="footer-item" href='https://www.linkedin.com/in/jaxxon-alta/'>
      <box-icon name='linkedin-square' type='logo' color='white' size='2em'></box-icon>
      <p>LinkedIn</p>
    </a>
    <a class="footer-item" href='https://lewagon-alumni.slack.com/team/U03C18ZG9DX'>
      <box-icon name='slack' type='logo' color='white' size='2em'></box-icon>
      <p>Slack</p>
    </a>
  </div>

  <div class="footer-row">
    <a class="footer-item cursor-pointer" onclick='clipboard("hello@jaxxon.dev")'>
      <box-icon id='email-icon' animation='none' type='solid' name='envelope'
      color="white" size='2em'></box-icon>
      <p data-text="📋 Copied to clipboard." class="tooltip"
         onmouseover="toggleAnimation('tada')"
         onmouseout="toggleAnimation('none')">
         hello@jaxxon.dev
      </p>
    </a>
  </div>

  <script>
    function toggleAnimation(input) {
      document.querySelector("#email-icon").attributes['animation'].nodeValue = input;
    }

    function clipboard(text) {
      navigator.clipboard.writeText(text);
      document.querySelector(".tooltip").classList.add("copied");
      setTimeout(() => {
        document.querySelector(".tooltip").classList.remove("copied");
      }, 3000);
    }
  </script>

</div>

app/views/shared/_header.html.erb
<div class="wrapper">
  <div class="header">
    <%= link_to 'jaxxon.dev', root_path, id: 'logo', class: 'button button-cta font-mono' %>
    <div class="header-row">
      <%= link_to 'Projects', '/projects', class: "button" %>
      <%= link_to 'About', '/about', class: "button" %>
      <%= link_to 'Contact', '/contact', class: "button button-cta" %>
    </div>
  </div>
</div>